apiVersion: v1
kind: Service
metadata:
  name: faithful-e2e-c
  namespace: colossus-faithful-e2e-c
  labels:
    app: faithful-e2e-c
    managed-by: colossus
spec:
  type: ClusterIP
  selector:
    app: faithful-e2e-c
  ports:
    - port: 80
      targetPort: 8080
